sudo: required
dist: xenial
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11
  - openjdk12
before_script:
  - echo $JAVA_OPTS
  - export JAVA_OPTS=-Xmx4G
install: true
script:
  - java -version
  - ulimit -a
  - TERM=dumb ./gradlew jpos:assemble jpos:check --info
after_success: .travis/update-gh-pages.sh
after_failure: .travis/update-gh-pages.sh
env:
  global:
    secure: ZWDnTNCsRaxOV4hPiWslj1ieKwYjuxBA4COHFVApxr8TBcQEwhPAzo+b+WbDsi45rJkk/Ee9Du0+mbT//x3TTK78fePg6EDk0WBSmWRUFC3eITgTmUJe7Qh5VOUZOdz9vFaYH8080/CB4VyygJuSp2XLte+S/MVSoXVVABrNggU=
notifications:
  slack:
    secure: opKU+4jJWYuhq5STCVW2cvxEq/1/xY17xpxGKoJXWA+RbhPo+viT5uJLmb67HwdmvQNwUVAW6uOLO7SDOmpGh5oAwpI74DrA0y6uEzN6GgzutZDBY5oCMRYCGi/5xNOuzDdsryDtSJvXWLxyCysnTrAqqQ9XdOnRK/ZqSIeQg+s=
matrix:
  allow_failures:
    - jdk: openjdk11
    - jdk: openjdk12
